---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - renovate.fartlab.dev
  resources:
  - renovateplatforms
  - renovateruns
  - renovatescans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - renovate.fartlab.dev
  resources:
  - renovateplatforms/finalizers
  - renovateruns/finalizers
  - renovatescans/finalizers
  verbs:
  - update
- apiGroups:
  - renovate.fartlab.dev
  resources:
  - renovateplatforms/status
  - renovateruns/status
  - renovatescans/status
  verbs:
  - get
  - patch
  - update
