apiVersion: renovate.fartlab.dev/v1alpha1
kind: RenovatePlatform
metadata:
  labels:
    app.kubernetes.io/name: kube
    app.kubernetes.io/managed-by: kustomize
  name: renovateplatform-sample
spec:
  # TODO(user): Add fields here
